spring:
  application:
    name: hcd-user
  profiles:
    active: dev
  config:
    import:
      - nacos:${spring.application.name}
      - nacos:hcd-common
  cloud:
    nacos:
      server-addr: localhost:8847
      username: nacos
      password: nacos
      config:
        namespace: 8a19b7dd-7c6e-4a98-8bcf-b81ebd4aad2c
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        namespace: 8a19b7dd-7c6e-4a98-8bcf-b81ebd4aad2c
        group: DEFAULT_GROUP

# 设置端口
server:
  port: 8081

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# Knife4j 增强配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-apis: true
    enable-filter-multipart-api-method-type: POST
    enable-request-cache: true
    enable-host: false
    enable-home-custom: true
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
  documents:
    - name: 用户服务API文档
      locations: classpath:markdown/
      group: 用户管理
  basic:
    enable: false