upstream frontend_mgmt {
    server hcd-frontend-mgmt:80;
}

server {
    listen 80;
    server_name localhost;

    # 前端管理界面
    location /mgmt/ {
        proxy_pass http://frontend_mgmt/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 默认根路径
    location / {
        return 301 /mgmt/;
    }
}